### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by ghost** [martinribelotta/elog#1]
Hey I was looking at this library and I would like to use it in a closed-source application. I was wondering if you have any licensing information available that could help me evaluate this library.

Btw amazing work :)

**Comment by martinribelotta** [comment]
Hi! i'm sorry for the ommision, the idea is to use a permisive MIT licence. The only problem with this is that some non-essential files (like linker script and startup file) is licenced under GPL.

I queue the rewrite of ld script and startup code and add LICENCE file (and header licence in *.h/*.c) for doing in few days (when my daily work allows me)

meanwhile you can go testing the code and feel free to post any enancement or issue to resolve

**Comment by ghost** [comment]
@martinribelotta we could help you with the rewrite of the ld script and startup code if you can make an issue with your intent if that helps speed things up

**Comment by martinribelotta** [comment]
Added a MIT licence
